### I
- transform - square
- imp; bins mean
- norm; z score

In [1]:
import Configure_Dataset 
df, y1, y2 = Configure_Dataset.configure('Competition1_raw_data.xlsx')
df.head(10)


C1   C2        C4       C7  %_long_sentences  %_long_words  \
0  122.0  1.0  0.029074   51.345          0.640426      0.054250   
1  259.0  0.0 -0.013352   25.936          0.644753      0.051395   
2   90.0  1.0  0.020715    7.378          0.636816      0.061764   
3  209.0  1.0  0.020023    8.526          0.539634      0.061630   
4   80.0  1.0 -0.034895  632.298          0.587413      0.048550   
5   94.0  1.0 -0.057556  197.591          0.643137      0.045280   
6  128.0  1.0  0.004106    5.146          0.765657      0.044295   
7   91.0  0.0  0.040620      NaN          0.826347           NaN   
8  100.0  1.0 -0.029316  279.600          0.540323      0.061905   
9  106.0  1.0 -0.024925  494.008          0.514286      0.050252   

   %_positive_words  %_negative_words  %_uncertain_words  C3'        C5'  \
0          0.004875          0.009199           0.010929    1   3.864345   
1          0.003258          0.011105           0.010876    0  12.028832   
2          0.011593          0.006271           0.011403    0   3.369134   
3          0.009686          0.007144           0.013319    0   3.299697   
4          0.004518          0.010047           0.011261    1   3.726269   
5          0.003445          0.005334           0.010056    1   5.724394   
6          0.005204          0.006727           0.008567    0   3.463095   
7          0.004899          0.010689           0.010868    0   2.421469   
8          0.003915          0.008371           0.015797    0   4.816591   
9          0.008868          0.009853           0.016094    1   3.056608   

         C6'  one_hot_Manufacturing  one_hot_Other  one_hot_Public Services  
0  11.111111                      1              0                        0  
1   0.000000                      1              0                        0  
2   0.000000                      1              0                        0  
3   0.000000                      1              0                        0  
4   5.000000                      0              0                        1  
5   0.000000                      0              0                        1  
6   0.000000                      1              0                        0  
7   0.000000                      1              0                        0  
8   0.000000                      0              0                        1  
9   0.000000                      1              0                        0

In [2]:
import ImputeUsingBins
df = ImputeUsingBins.impute_bin_mean(df)

In [3]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df))
print(z)

[[0.181588   0.40499526 0.65456609 ... 1.00303491 0.34719345 0.80622577]
 [0.71558631 2.46916468 0.61977651 ... 1.00303491 0.34719345 0.80622577]
 [0.39114697 0.40499526 0.40347956 ... 1.00303491 0.34719345 0.80622577]
 ...
 [0.24707518 2.46916468 0.69514699 ... 1.00303491 0.34719345 0.80622577]
 [0.46973158 0.40499526 0.75098528 ... 0.99697427 2.88023864 0.80622577]
 [0.8596581  0.40499526 0.52279663 ... 1.00303491 0.34719345 0.80622577]]


In [4]:
threshold = 3
print(np.where(z > 3))

(array([  2,  32,  47,  49,  57,  64,  64,  80,  81,  92, 104, 105, 109,
       112, 137, 157, 157, 157, 166, 177, 177, 184, 184, 184, 196, 199,
       214, 221, 243, 252, 263, 267, 267, 282, 283, 290, 302, 303, 322,
       371, 374, 380, 385, 388, 399, 402, 402, 411, 421, 425, 435, 455,
       459, 463, 464, 495, 499, 499, 526, 526, 530, 536, 563, 568, 580,
       607, 611, 644, 652]), array([ 6, 11,  7,  8, 10,  0, 11,  6,  0,  8,  5,  2,  8,  7,  0,  3,  7,
       10,  3,  3,  6,  5,  6,  8,  0, 10,  0,  0,  4,  6,  8,  3,  7,  3,
        3,  7, 11,  2, 11,  8,  6,  0,  0, 11,  0,  8, 11,  7,  0,  8, 11,
       11, 11,  0,  4,  0,  3,  7,  5,  6, 11,  0,  6,  7,  7,  0,  8,  0,
       11]))


In [5]:
df = df[(z < 3).all(axis=1)]

In [6]:
from Transform import skew_transform_square
df = skew_transform_square(df)

In [7]:
df.isnull().sum()

C1                         0
C2                         0
C4                         0
C7                         0
%_long_sentences           0
%_long_words               0
%_positive_words           0
%_negative_words           0
%_uncertain_words          0
C3'                        0
C5'                        0
C6'                        0
one_hot_Manufacturing      0
one_hot_Other              0
one_hot_Public Services    0
dtype: int64

In [8]:
df.head(10)

C1   C2        C4         C7  %_long_sentences  %_long_words  \
0   11.045361  1.0  0.029074   7.165543          0.640426      0.054250   
1   16.093477  0.0 -0.013352   5.092740          0.644753      0.051395   
3   14.456832  1.0  0.020023   2.919932          0.539634      0.061630   
4    8.944272  1.0 -0.034895  25.145536          0.587413      0.048550   
5    9.695360  1.0 -0.057556  14.056707          0.643137      0.045280   
6   11.313708  1.0  0.004106   2.268480          0.765657      0.044295   
7    9.539392  0.0  0.040620  18.716455          0.826347      0.053154   
8   10.000000  1.0 -0.029316  16.721244          0.540323      0.061905   
9   10.295630  1.0 -0.024925  22.226291          0.514286      0.050252   
10   9.949874  1.0  0.015487   0.565685          0.545455      0.066517   

    %_positive_words  %_negative_words  %_uncertain_words  C3'       C5'  \
0           0.069818          0.095911           0.010929    1  1.965794   
1           0.057080          0.105380           0.010876    0  3.468261   
3           0.098420          0.084521           0.013319    0  1.816507   
4           0.067215          0.100236           0.011261    1  1.930355   
5           0.058691          0.073032           0.010056    1  2.392571   
6           0.072137          0.082017           0.008567    0  1.860939   
7           0.069995          0.103390           0.010868    0  1.556107   
8           0.062574          0.091493           0.015797    0  2.194673   
9           0.094170          0.099264           0.016094    1  1.748316   
10          0.070784          0.084164           0.012094    0  1.595834   

         C6'  one_hot_Manufacturing  one_hot_Other  one_hot_Public Services  
0   3.333333                      1            0.0                        0  
1   0.000000                      1            0.0                        0  
3   0.000000                      1            0.0                        0  
4   2.236068                      0            0.0                        1  
5   0.000000                      0            0.0                        1  
6   0.000000                      1            0.0                        0  
7   0.000000                      1            0.0                        0  
8   0.000000                      0            0.0                        1  
9   0.000000                      1            0.0                        0  
10  0.000000                      1            0.0                        0

In [9]:
from Normalize import z_score
df=z_score(df)
df.head()

0         1         2         3         4         5         6   \
0  0.008676  0.411413  0.662990 -0.632672  0.175047  0.368455 -0.135365   
1  1.519774 -2.430647 -0.649042 -0.804428  0.236350 -0.071098 -1.279465   
2  1.029863  0.411413  0.383081 -0.984470 -1.252617  1.504884  2.433381   
3 -0.620262  0.411413 -1.315267  0.857177 -0.575857 -0.509146 -0.369167   
4 -0.395432  0.411413 -2.016076 -0.061660  0.213457 -1.012664 -1.134736   

         7         8         9         10        11        12        13  \
0  0.208676 -0.149337  1.028698  0.004901  1.225052  0.991715 -0.345225   
1  0.894500 -0.171174 -0.972103  3.272187 -0.732578  0.991715 -0.345225   
2 -0.616227  0.835841 -0.972103 -0.319741 -0.732578  0.991715 -0.345225   
3  0.521919 -0.012324  1.028698 -0.072166  0.580640 -1.008354 -0.345225   
4 -1.448287 -0.508914  1.028698  0.932976 -0.732578 -1.008354 -0.345225   

         14  
0 -0.798500  
1 -0.798500  
2 -0.798500  
3  1.252348  
4  1.252348

In [10]:
import Combine
I = Combine.combine(df, y1, y2)
I.head()

0         1         2         3         4         5         6  \
0  0.008676  0.411413  0.662990 -0.632672  0.175047  0.368455 -0.135365   
1  1.519774 -2.430647 -0.649042 -0.804428  0.236350 -0.071098 -1.279465   
2  1.029863  0.411413  0.383081 -0.984470 -1.252617  1.504884  2.433381   
3 -0.620262  0.411413 -1.315267  0.857177 -0.575857 -0.509146 -0.369167   
4 -0.395432  0.411413 -2.016076 -0.061660  0.213457 -1.012664 -1.134736   

          7         8         9        10        11        12        13  \
0  0.208676 -0.149337  1.028698  0.004901  1.225052  0.991715 -0.345225   
1  0.894500 -0.171174 -0.972103  3.272187 -0.732578  0.991715 -0.345225   
2 -0.616227  0.835841 -0.972103 -0.319741 -0.732578  0.991715 -0.345225   
3  0.521919 -0.012324  1.028698 -0.072166  0.580640 -1.008354 -0.345225   
4 -1.448287 -0.508914  1.028698  0.932976 -0.732578 -1.008354 -0.345225   

         14  Y1  Y2  
0 -0.798500   0   1  
1 -0.798500   1   0  
2 -0.798500   1   0  
3  1.252348   1   1  
4  1.252348   0   1

In [11]:
import pandas as pd
I.to_csv('./Datasets/I_ts_out_z.csv')