### I
- transform - square
- imp; bins mean
- norm; z score

In [1]:
import Configure_Dataset 
df, y1, y2 = Configure_Dataset.configure('Competition1_raw_data.xlsx')
df.head(10)
import pandas as pd

In [2]:
df.isnull().sum()

C1                          0
C2                          0
C4                          0
C7                         60
%_long_sentences            0
%_long_words                3
%_positive_words            3
%_negative_words            2
%_uncertain_words           2
C3'                         0
C5'                         0
C6'                         0
one_hot_Manufacturing       0
one_hot_Other               0
one_hot_Public Services     0
dtype: int64

In [3]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df))
print(z)

[[0.181588   0.40499526 0.65456609 ... 1.00303491 0.34719345 0.80622577]
 [0.71558631 2.46916468 0.61977651 ... 1.00303491 0.34719345 0.80622577]
 [0.39114697 0.40499526 0.40347956 ... 1.00303491 0.34719345 0.80622577]
 ...
 [0.24707518 2.46916468 0.69514699 ... 1.00303491 0.34719345 0.80622577]
 [0.46973158 0.40499526 0.75098528 ... 0.99697427 2.88023864 0.80622577]
 [0.8596581  0.40499526 0.52279663 ... 1.00303491 0.34719345 0.80622577]]


In [4]:
threshold = 3
print(np.where(z > 3))

(array([ 32,  57,  64,  64,  81, 105, 137, 157, 196, 199, 214, 221, 243,
       302, 303, 322, 380, 385, 388, 399, 402, 421, 435, 455, 459, 463,
       464, 495, 530, 536, 607, 644, 652]), array([11, 10,  0, 11,  0,  2,  0, 10,  0, 10,  0,  0,  4, 11,  2, 11,  0,
        0, 11,  0, 11,  0, 11, 11, 11,  0,  4,  0, 11,  0,  0,  0, 11]))


/opt/tljh/user/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


In [5]:
df=df.replace(np.where(z > 3), np.NaN)

/opt/tljh/user/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


In [6]:
import ImputeUsingBins
df = ImputeUsingBins.impute_bin_mean(df)

ValueError: Length of passed values is 660, index implies 0

In [ ]:
threshold = 3
print(np.where(z > 3))

In [ ]:
df1 = df[["C2","C3'","one_hot_Manufacturing", "one_hot_Other", "one_hot_Public Services"]]
df2 = df[["C1","C4","C7","%_long_sentences","%_long_words","%_positive_words","%_negative_words","%_uncertain_words","C5'","C6'"]]


In [ ]:
df.head(10)

In [ ]:
from Transform import skew_transform_log
df2 = skew_transform_log(df2)

In [ ]:
from Normalize import z_score
df2=z_score(df2)
#df1=z_score(df1)
df2.head()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:

correl = df.corr()

cmap = sns.diverging_palette(240,10, as_cmap = 'true')
sns.heatmap(correl, xticklabels = correl.columns.values, yticklabels = correl.columns.values, cmap = cmap)
plt.title('coefficient correlation')

In [ ]:
df_col = pd.concat([df1,df2], axis=1)
#df_col = df_col.rename(lambda x: x[1:], axis='columns')
df_col

In [ ]:
import Combine
I = Combine.combine(df_col, y1, y2)
I.head()

In [ ]:
import pandas as pd
I.to_csv('./Datasets/I_zzzz.csv')

In [ ]:
array = I.values

X = array[:,:-2] #features
Y1 = array[:,-2:-1] #target
Y2 = array[:,-1] #target

In [ ]:
# Import your necessary dependencies
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [ ]:
# Feature extraction
model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(X, Y1)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

In [ ]:
# Feature extraction
model = LogisticRegression()
rfe = RFE(model,3)
fit = rfe.fit(X, Y1)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))